---
title: 'Reproducible Research: Peer Assessment 1'
output:
  word_document: default
  pdf_document: default
  html_document:
    keep_md: yes
---


## Loading and preprocessing the data
```{r load_and_preprocess}
unzip("activity.zip")
activity <- read.csv("activity.csv")
activity <- activity[complete.cases(activity),]
```



## What is mean total number of steps taken per day?

```{r dialy_steps, message=FALSE}
# library(sqldf)
# daily_steps <- sqldf("select date, sum(steps) total_steps from activity where steps != 'NA' and date != 'NA' group by date order by date")
# daily_steps
# hist(daily_steps$total_steps,  breaks = 10 ,col="red", xlab = "Total Daily Steps", main = "Histogram of Total Daily Steps")

```

```{r dialy_steps_2, message=FALSE}
library(plyr)
daily_steps <- ddply(activity, c("date"), summarise, total_steps = sum(steps))
daily_steps
hist(daily_steps$total_steps,  breaks = 10 ,col="red", xlab = "Total Daily Steps", main = "Histogram of Total Daily Steps")
mean_daily_steps <- prettyNum(round(mean(daily_steps$total_steps), 0), big.mark = ",")
median_daily_steps <- prettyNum(median(daily_steps$total_steps), big.mark = ",")
```
The averge number of steps taken was `r mean_daily_steps` and the median was `r median_daily_steps`.


## What is the average daily activity pattern?
```{r activity_pattern}
activity_pattern <- ddply(activity, c("interval"), summarize, average_steps = mean(steps))
plot(activity_pattern, type="l", col="red", xlab="Time Interval", ylab="Average Steps", main="Average Steps Taken per Time Interval")
```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
